### PR TITLE
Switches the default source to ESM style

### PR DESCRIPTION
**Pull request by samlev**
CJS using `require('axios')` was causing issues in modern Vite production builds, as Rollup was tree-shaking axios and removing the `post` method.

This led to very difficult-to-diagnose problems where the production build (i.e. what had to run on Vapor) was failing to upload files.

For whatever reason `microbundle` wasn't producing a valid ESM output, but keeping the code as ESM lets `microbundle` product a valid CJS output.

### CODE REVIEW

**Comment by MarcEspiard** [comment]
Hi @samlev @taylorotwell,

Could this MR be tagged and released please?
Our uploads are failing since updating to 0.7.0

Cheers

**Comment by samlev** [comment]
@MarcEspiard it's not up to me :)

**Comment by devinfd** [comment]
@taylorotwell Please tag a new version of this package so this MR can be used. Until then uploads are failing 😢

**Comment by pintend** [comment]
`rm -rf node_modules package-lock.json && npm install && npx vite build`

**Comment by amcfarlane** [comment]
Hi, probably not the correct place for this. But as I understand, this fix was released/tagged in 0.7.1? We have updated and are still getting an error in production for a missing 'post' method. Reverting to '0.6.0' fixes the issue. Should it be fixed in 0.7.1? Thanks

**Comment by vorban** [comment]
Hi! I confirm this is not working for us @amcfarlane.

I have setup a fresh Laravel 11 installation with the latest version of vapor-js 0.7.1, to showcase the issue: [https://github.com/vorban/vapor-non-deterministic](https://github.com/vorban/vapor-non-deterministic)

It only takes the addition of 1 lib (alpinejs here, but can be reproduced with other libs), for vite to tree-shake `axios.post` out of the build.

In multiple production environments running on Vapor, we have a non-deterministic build issue because of vite's parallelization over multiple js files. It's basically a coinflip and sometimes post is tree-shaken, sometimes not.

As far as I can tell, this might be because of [this line](https://github.com/laravel/vapor-js/blob/d1c9095fb92639510f918042c58f5fc4e832e999/package.json#L17C3-L17C35) in package.json:
```json
"main": "dist/laravel-vapor.js",
```
Because clearly, this dist file ([link](https://github.com/laravel/vapor-js/blob/d1c9095fb92639510f918042c58f5fc4e832e999/dist/laravel-vapor.js)) is still using `require()`:
```js
var t=e(require("axios"))
```

I seem to be able to fix the issue by updating `package.json` to:
```json
"main": "dist/laravel-vapor.modern.js"
```
However I'm unaware of any side-effects.

I'll let y'all some time to catch any issue with this recap, if all good / no answer by the end of the week, I'll make a new PR to implement this change 😄

**Comment by samlev** [comment]
Uggh. It looks like microbundle is still preferring CJS over ESM for the main package.

At least there's a valid MJS bundle being produced now, so you _should_ be able to use:

```js
import Vapor from 'laravel-vapor/dist/laravel-vapor.esm'
```

**Comment by vorban** [comment]
@samlev it seems to work, thanks for the tip!

Still, this is not ideal as the default import will fails. I'll end up submitting a PR by next week I guess 😉

**Pull request merged**
